### PR TITLE
macOS build fixes

### PR DESCRIPTION
**Pull request by itwysgsl**
Little fixes here and there.

### CODE REVIEW

**Comment by itwysgsl** [comment]
Fixes for some of this issues https://github.com/bschn2/rainforest/issues/12

**Comment by bschn2** [comment]
Thank you Sir!

**Comment by aivve** [comment]
This version won't compile on MS Visual Studio due to various errors:
```
error C2065: '__asm__': undeclared identifier
```
in rfv2_div_mod
```
error LNK2019: unresolved external symbol __builtin_clrsbl referenced in function rfv2_rambox
```

**Comment by bschn2** [comment]
Hello Sir,

Indeed from what I'm reading MS C uses a totally different syntax for assembly that is not compatible with what we have here, and which will not be easy to adapt. Could you please check if the following fixes the issue for you? I'll merge it if so.

```
--- a/rfv2.h
+++ b/rfv2.h
@@ -36,6 +36,11 @@
 
 #include <stdint.h>
 
+// MSVC's asm directive is totally different
+#ifdef MSC_VER
+#define RF_NOASM
+#endif
+
 #define RFV2_RAMBOX_SIZE (96*1024*1024/8)
 
 int rfv2_hash(void *out, const void *in, size_t len, void *rambox, const void *rambox_template);
```

**Pull request merged**
