### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by itwysgsl**
Some minor fixes for issues described here https://github.com/bschn2/rainforest/issues/12

### CODE REVIEW

**Comment by bschn2** [comment]
Hello Sir,
thanks for dealing with this. Please note that for the first patch, the msg8 local variable should be declared const, as otherwise you're explicitly turning a read-only variable to a read-write one. And the uint32_t cast in the call to rf_crc32_8() is not needed. It would help me if you could adjust your patch as I don't see how to edit patches in pull requests.

**Comment by itwysgsl** [comment]
@bschn2 done, can you check it?

**Comment by wtarreau** [comment]
@bschn2 when you visualize the patches, a pen appears, I suspect you can edit them in this mode. After all github supports rebase merges, so it must support editing the patches as well.

@itwysgsl I'm seeing an extra file merged by accident in your second patch. Also the good practice (I don't know for this project) is to fix patches instead of submitting a fix for pending patches, this avoids having intermediary states which possibly cause trouble. This case happens when you try to figure what modification broke something, by using "git bisect". You may end up in the middle of two patches which broke by accident, making it difficult or impossible to finish the bisect session due to an extra error merged in the middle. Normally on your side you do this either using different branches or by modifying your last patches using "git rebase -i master" or "git commit --amend" when it's the last one. Just my two cents!

**Comment by itwysgsl** [comment]
@wtarreau yes, my bad, I accidentally commited my test binary. I also agree that fixing patch instead of submitting a fix for patch is bad practice. Should be fixed by now :)

**Comment by wtarreau** [comment]
Yes, this looks much better indeed, thank you for taking it positively ;-)
Bill? I quickly checked and these patches are good.

**Comment by bschn2** [comment]
Thank you Gentlemen.

**Pull request merged**
