### PR TITLE
functions renaming + cpuminer patch updste

### PR DESCRIPTION
**Pull request by MikeMurdo**
renamed rf256, rf_* to rfv2_* to stop confusion. Except aes/crc which are standalone. Renamed files as well. Rediffed the cpuminer patch and removed main files from the patch. Now they have to be copied manually so no more patch updates for algo tweaks. Good idea by the way regarding the multiple C files  including themselves as matryoshka dolls! A single file to change in the Makefile and that was done!

### CODE REVIEW

**Comment by bschn2** [comment]
Hello Sir!
Thank you for working on this! I'm not decided yet whether I'd want to rename the functions before people start to integrate them or after, as I don't want to require more efforts from them. But I also see the value in the updated patch. Let's see if anyone complains about the rename before merging this. In this case we'd also have to remove the outdated comments about performance in the code.
Thank you!
B.S.

**Comment by MikeMurdo** [comment]
I don't see why anyone would complain about the renaming! Trying to force the updated code into an already patched project without renaming it is a real PITA. Some parts change others not you don't know what's up to date.

**Comment by jdelorme3** [comment]
confirmed!

**Comment by bschn2** [comment]
OK fair enough. Let's not wait unduly then. Thank you!

**Pull request merged**
